language: c
matrix:
    include:
        - name: Linux (gcc)
          os: linux
          compiler: gcc
        - name: Linux (clang)
          os: linux
          compiler: clang
sudo: false
before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo add-apt-repository -y ppa:longsleep/golang-backports; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install golang-1.13-go; fi
install:
    - if [ $TRAVIS_OS_NAME = linux ]; then export PATH=/usr/lib/go-1.13/bin:$PATH; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then export GOPATH=/usr/lib/go-1.13:$GOPATH; fi
    - if [ $TRAVIS_OS_NAME = linux ]; then export GOROOT=/usr/lib/go-1.13; fi
before_script:
    - git submodule init
    - git submodule update --recursive
    - cmake .
script:
    - make
